services:
  postgres:
    image: postgres:15
    container_name: ems_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_password
      POSTGRES_DB: ems_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems_user -d ems_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ems_pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_SERVER_AUTOSTART: "True"
      PGADMIN_SERVER_GROUP: "ems_db"
      PGADMIN_SERVER_NAME: "ems_db"
      PGADMIN_SERVER_HOST: "postgres"
      PGADMIN_SERVER_PORT: 5432
      PGADMIN_SERVER_DB: "ems_db"
      PGADMIN_SERVER_USERNAME: "ems_user"
      PGADMIN_SERVER_PASSWORD: "ems_password"
    ports:
      - "6554:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ems_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__PGConnection: "Host=postgres;Port=5432;Database=ems_db;Username=ems_user;Password=ems_password"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:7026"  # Fixed syntax
    ports:
      - "7026:7026"
    expose:
      - "7026"
    restart: unless-stopped
    volumes:
      - ./certs:/https

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ems_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    expose:
      - "5173"
    volumes:
    - ./certs:/etc/ssl/certs:ro
    - ./certs:/etc/ssl/private:ro

volumes:
  pgdata:
  pgadmin_data: