version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ems_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_password
      POSTGRES_DB: ems_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems_user -d ems_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ems_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__PGConnection: "Host=postgres;Port=5432;Database=ems_db;Username=ems_user;Password=ems_password"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:7026"  # Fixed syntax
    ports:
      - "7026:7026"
    expose:
      - "7026"
    restart: unless-stopped
    volumes:
      - ./certs:/https

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ems_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    expose:
      - "5173"
    volumes:
    - ./certs:/etc/ssl/certs:ro
    - ./certs:/etc/ssl/private:ro

volumes:
  pgdata: