/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as SetupManagerProfileRouteImport } from './routes/setup/manager-profile'
import { Route as SetupEmployeeProfileRouteImport } from './routes/setup/employee-profile'
import { Route as ManagerPromoteRouteImport } from './routes/manager/promote'
import { Route as ManagerLeaveApplicationsRouteImport } from './routes/manager/leave-applications'
import { Route as ManagerEditMyProfileRouteImport } from './routes/manager/edit-my-profile'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthPassresetRouteImport } from './routes/auth/passreset'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ManagerEmployeeNameRouteImport } from './routes/manager/employee/$name'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const SetupManagerProfileRoute = SetupManagerProfileRouteImport.update({
  id: '/manager-profile',
  path: '/manager-profile',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupEmployeeProfileRoute = SetupEmployeeProfileRouteImport.update({
  id: '/employee-profile',
  path: '/employee-profile',
  getParentRoute: () => SetupRouteRoute,
} as any)
const ManagerPromoteRoute = ManagerPromoteRouteImport.update({
  id: '/promote',
  path: '/promote',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerLeaveApplicationsRoute =
  ManagerLeaveApplicationsRouteImport.update({
    id: '/leave-applications',
    path: '/leave-applications',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerEditMyProfileRoute = ManagerEditMyProfileRouteImport.update({
  id: '/edit-my-profile',
  path: '/edit-my-profile',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPassresetRoute = AuthPassresetRouteImport.update({
  id: '/passreset',
  path: '/passreset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ManagerEmployeeNameRoute = ManagerEmployeeNameRouteImport.update({
  id: '/employee/$name',
  path: '/employee/$name',
  getParentRoute: () => ManagerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/setup': typeof SetupRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passreset': typeof AuthPassresetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/manager/edit-my-profile': typeof ManagerEditMyProfileRoute
  '/manager/leave-applications': typeof ManagerLeaveApplicationsRoute
  '/manager/promote': typeof ManagerPromoteRoute
  '/setup/employee-profile': typeof SetupEmployeeProfileRoute
  '/setup/manager-profile': typeof SetupManagerProfileRoute
  '/manager/': typeof ManagerIndexRoute
  '/manager/employee/$name': typeof ManagerEmployeeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/setup': typeof SetupRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passreset': typeof AuthPassresetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/manager/edit-my-profile': typeof ManagerEditMyProfileRoute
  '/manager/leave-applications': typeof ManagerLeaveApplicationsRoute
  '/manager/promote': typeof ManagerPromoteRoute
  '/setup/employee-profile': typeof SetupEmployeeProfileRoute
  '/setup/manager-profile': typeof SetupManagerProfileRoute
  '/manager': typeof ManagerIndexRoute
  '/manager/employee/$name': typeof ManagerEmployeeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/setup': typeof SetupRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passreset': typeof AuthPassresetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/manager/edit-my-profile': typeof ManagerEditMyProfileRoute
  '/manager/leave-applications': typeof ManagerLeaveApplicationsRoute
  '/manager/promote': typeof ManagerPromoteRoute
  '/setup/employee-profile': typeof SetupEmployeeProfileRoute
  '/setup/manager-profile': typeof SetupManagerProfileRoute
  '/manager/': typeof ManagerIndexRoute
  '/manager/employee/$name': typeof ManagerEmployeeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manager'
    | '/setup'
    | '/about'
    | '/unauthorized'
    | '/auth/login'
    | '/auth/passreset'
    | '/auth/signup'
    | '/manager/edit-my-profile'
    | '/manager/leave-applications'
    | '/manager/promote'
    | '/setup/employee-profile'
    | '/setup/manager-profile'
    | '/manager/'
    | '/manager/employee/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/about'
    | '/unauthorized'
    | '/auth/login'
    | '/auth/passreset'
    | '/auth/signup'
    | '/manager/edit-my-profile'
    | '/manager/leave-applications'
    | '/manager/promote'
    | '/setup/employee-profile'
    | '/setup/manager-profile'
    | '/manager'
    | '/manager/employee/$name'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/manager'
    | '/setup'
    | '/about'
    | '/unauthorized'
    | '/auth/login'
    | '/auth/passreset'
    | '/auth/signup'
    | '/manager/edit-my-profile'
    | '/manager/leave-applications'
    | '/manager/promote'
    | '/setup/employee-profile'
    | '/setup/manager-profile'
    | '/manager/'
    | '/manager/employee/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  SetupRouteRoute: typeof SetupRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/setup/manager-profile': {
      id: '/setup/manager-profile'
      path: '/manager-profile'
      fullPath: '/setup/manager-profile'
      preLoaderRoute: typeof SetupManagerProfileRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/employee-profile': {
      id: '/setup/employee-profile'
      path: '/employee-profile'
      fullPath: '/setup/employee-profile'
      preLoaderRoute: typeof SetupEmployeeProfileRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/manager/promote': {
      id: '/manager/promote'
      path: '/promote'
      fullPath: '/manager/promote'
      preLoaderRoute: typeof ManagerPromoteRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/leave-applications': {
      id: '/manager/leave-applications'
      path: '/leave-applications'
      fullPath: '/manager/leave-applications'
      preLoaderRoute: typeof ManagerLeaveApplicationsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/edit-my-profile': {
      id: '/manager/edit-my-profile'
      path: '/edit-my-profile'
      fullPath: '/manager/edit-my-profile'
      preLoaderRoute: typeof ManagerEditMyProfileRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/passreset': {
      id: '/auth/passreset'
      path: '/passreset'
      fullPath: '/auth/passreset'
      preLoaderRoute: typeof AuthPassresetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/manager/employee/$name': {
      id: '/manager/employee/$name'
      path: '/employee/$name'
      fullPath: '/manager/employee/$name'
      preLoaderRoute: typeof ManagerEmployeeNameRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPassresetRoute: typeof AuthPassresetRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthPassresetRoute: AuthPassresetRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerEditMyProfileRoute: typeof ManagerEditMyProfileRoute
  ManagerLeaveApplicationsRoute: typeof ManagerLeaveApplicationsRoute
  ManagerPromoteRoute: typeof ManagerPromoteRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerEmployeeNameRoute: typeof ManagerEmployeeNameRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerEditMyProfileRoute: ManagerEditMyProfileRoute,
  ManagerLeaveApplicationsRoute: ManagerLeaveApplicationsRoute,
  ManagerPromoteRoute: ManagerPromoteRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerEmployeeNameRoute: ManagerEmployeeNameRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface SetupRouteRouteChildren {
  SetupEmployeeProfileRoute: typeof SetupEmployeeProfileRoute
  SetupManagerProfileRoute: typeof SetupManagerProfileRoute
}

const SetupRouteRouteChildren: SetupRouteRouteChildren = {
  SetupEmployeeProfileRoute: SetupEmployeeProfileRoute,
  SetupManagerProfileRoute: SetupManagerProfileRoute,
}

const SetupRouteRouteWithChildren = SetupRouteRoute._addFileChildren(
  SetupRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  SetupRouteRoute: SetupRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
